name: klauncher
description: "Simple android desktop"
publish_to: 'none'

version: 1.2.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  device_apps: ^2.2.0
  google_fonts: ^6.1.0
  provider: ^6.1.1
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
